name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential autoconf automake libtool
    - name: Make configure script executable
      run: chmod +x ./configure
    - name: configure
      run: ./configure --verbose
    - name: make
      run: make -e
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
